# Generated by Django 4.2.4 on 2024-01-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StuInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField()),
                ('Name', models.CharField(max_length=200)),
                ('Address', models.TextField(max_length=300)),
            ],
        ),
    ]
